// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaB_7M8yOZbPDZWDMqL3zmUKRwBJXnWOA',
    appId: '1:109227683554:web:44b2fad6d9eaa24a53b8bb',
    messagingSenderId: '109227683554',
    projectId: 'quantam-innovation',
    authDomain: 'quantam-innovation.firebaseapp.com',
    storageBucket: 'quantam-innovation.appspot.com',
    measurementId: 'G-4MZ60ZJQQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-H7cyfEPFvHTb5zwCPJQ6aHZS0zoJmCY',
    appId: '1:109227683554:android:ba7fc5118406a46453b8bb',
    messagingSenderId: '109227683554',
    projectId: 'quantam-innovation',
    storageBucket: 'quantam-innovation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXy6NARfUgipKTEatRrs1Qn-d1qVYzsY',
    appId: '1:109227683554:ios:9bf5a856e82dee8653b8bb',
    messagingSenderId: '109227683554',
    projectId: 'quantam-innovation',
    storageBucket: 'quantam-innovation.appspot.com',
    iosClientId: '109227683554-3dn3a5kfcmvisnjshus1t0shg51mvcdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantamInnovation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXy6NARfUgipKTEatRrs1Qn-d1qVYzsY',
    appId: '1:109227683554:ios:9bf5a856e82dee8653b8bb',
    messagingSenderId: '109227683554',
    projectId: 'quantam-innovation',
    storageBucket: 'quantam-innovation.appspot.com',
    iosClientId: '109227683554-3dn3a5kfcmvisnjshus1t0shg51mvcdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantamInnovation',
  );
}
